### ISSUE TITLE
Final MVP Checklist !

### ISSUE THREAD

**Issue by deanmayne** [deanmayne/marcheauxpuces#4]
### 1.New account creation, login, and guest/demo login (2 days to complete)
- [x] Users have the ability to create new accounts
- [ ] delete profiles/accounts (with the exception of the guest_user)
- [x] Use existing accounts to login.
- [x] A guest/demo login button to allow for full site functionality without signing up.
### 2.Hosting on Heroku (should take a few hours to complete at most)
- [x] The entirety of the finalize application can be accessed through a link to where it is hosted on Heroku.com
### 3.Product Listings (2 days to complete)
- [x] Users have the ability to list products under their store.
- [x] Products have a name, description, price, shipping, and ship from location information.
- [x] The above attributes have the ability to be edited.
- [x] Users have the ability to delete products from their store.
### 4.Shopping Cart (2 days to complete)
- [x] Users have the ability to add products to and view their shopping carts.
- [x] Conversely, users have the ability to remove items from their shopping carts.
### 5.Comments / Reviews (1 day to complete)
- [ ] Users have the ability to leave reviews on products that they do not own.
### 6.Search (1 day to complete)
- [x] Users have the ability to search the catalogue of products from all stores across the site.
### 7.Bonus: Categories (1 day to complete)
- [ ] Key product category links should reside at the top of any give page on the site.
- [ ] Such as: Home & Lifestyle, Art and Collectibles, Clothing, etc.
### 8.Bonus: Favorites (1 day to complete)
- [x] Users have a unified page of products and stores that they have favorited.
- [x] Add to favorites (with heart icon change on Product Show Page)
- [x] Remove from favorites (with heart icon change on Product Show Page)
### 9.Production README (should only take 1-2 hours to complete at most)
- [ ] Completed and formatted correctly.

**Comment by mkayys** [comment]
![Screen Shot 2020-12-17 at 5 42 10 PM](https://user-images.githubusercontent.com/48598856/102563933-44944200-408f-11eb-8b44-1769878a620f.png)
- styling and deletion doesn't work: console error

![Screen Shot 2020-12-17 at 5 44 59 PM](https://user-images.githubusercontent.com/48598856/102564112-9a68ea00-408f-11eb-8367-a6b2ca4f35e2.png)
- editing a product isn't prefilled with the previous product info
- suggestion: add functionality for user to upload photos for their products; also when deleting a product, should redirect to your products page

- images and product name are a bit mismatched
- images change on refresh

![Screen Shot 2020-12-17 at 5 48 14 PM](https://user-images.githubusercontent.com/48598856/102564349-1c591300-4090-11eb-9f0f-581ddb926db2.png)
- filtering by category seems to not work; got benches and plates with `Clothing & Shoes`

- based on your MVP, it says " leave reviews on products that they have purchased" --> looks like I can leave a review on any product
- missing checking out a cart?

**Comment by deanmayne** [comment]
Fixed the bug for the delete account functionality (but still needs styling that was a miss on my part)
